import uuid

from sqlalchemy import Integer, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.types import TIMESTAMP
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class Document(Base):
    __tablename__ = "documents"

    # UUID primary key — random, unguessable, safe to expose in URLs.
    # generated by Python (default=uuid.uuid4) not the DB, so we always
    # know the ID before the INSERT completes (useful for async flows).
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    # Original filename shown in the UI.
    filename: Mapped[str] = mapped_column(Text, nullable=False)

    # S3 object key — null until Phase 1d when we add direct S3 uploads.
    # Designed in now so we won't need a schema change later.
    s3_key: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Processing state machine: pending → processing → complete | failed
    # Using TEXT rather than a Postgres ENUM so adding new states doesn't
    # require a schema migration.
    status: Mapped[str] = mapped_column(Text, nullable=False, default="pending")

    # Populated when status = "failed". Shown in the UI so users know why.
    error: Mapped[str | None] = mapped_column(Text, nullable=True)

    # How many chunks were indexed. Useful for debugging retrieval quality.
    chunks_indexed: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # server_default=func.now() means the DB sets this on INSERT if not provided.
    # TIMESTAMP(timezone=True) always stores UTC — convert to user's timezone at display time.
    created_at: Mapped[str] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[str] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )
